nome = input('Qual o seu nome completo:').strip()
print('Seu nome em maiúsculo é {}'.format(nome.upper()))
print('Seu nome em minúsculo é'.format(nome.lower()))
print('Existem {} caracteres no seu nome'.format(len(nome)-nome.count('  ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))